services:
  apache:
    depends_on:
      # onlyoffice:
      #   condition: "service_started"
      #   required: false
      collabora:
        condition: "service_started"
        required: false
      talk:
        condition: "service_started"
        required: false
      notify-push:
        condition: "service_started"
        required: false
      whiteboard:
        condition: "service_started"
        required: false
      nextcloud:
        condition: "service_started"
        required: false
    image: "ghcr.io/nextcloud-releases/aio-apache:20251031_122139"
    user: "33"
    init: true
    healthcheck:
      start_period: "0s"
      test: "/healthcheck.sh"
      interval: "30s"
      timeout: "30s"
      start_interval: "5s"
      retries: 3
    expose:
    - "${NC_APACHE_PORT}/tcp"
    - "${NC_APACHE_PORT}/udp"
    environment:
    - "NC_DOMAIN=${NC_DOMAIN}"
    - "NEXTCLOUD_HOST=nextcloud"
    - "APACHE_HOST=apache"
    - "COLLABORA_HOST=collabora"
    - "TALK_HOST=talk"
    - "APACHE_PORT=${NC_APACHE_PORT}"
    - "ONLYOFFICE_HOST=onlyoffice"
    - "TZ=${NC_TIMEZONE}"
    - "APACHE_MAX_SIZE=${NC_APACHE_MAX_SIZE}"
    - "APACHE_MAX_TIME=${NC_NEXTCLOUD_MAX_TIME}"
    - "NOTIFY_PUSH_HOST=notify-push"
    - "WHITEBOARD_HOST=whiteboard"
    volumes:
    - "nextcloud:/var/www/html:ro"
    - "apache:/mnt/data:rw"
    restart: "unless-stopped"
    read_only: true
    tmpfs:
    - "/var/log/supervisord"
    - "/var/run/supervisord"
    - "/usr/local/apache2/logs"
    - "/tmp"
    - "/home/www-data"
    cap_drop:
    - "NET_RAW"
    networks:
    - "core_cloudflared"
    - "nextcloud"

  database:
    image: "ghcr.io/nextcloud-releases/aio-postgresql:20251031_122139"
    user: "999"
    init: true
    healthcheck:
      start_period: "0s"
      test: "/healthcheck.sh"
      interval: "30s"
      timeout: "30s"
      start_interval: "5s"
      retries: 3
    expose:
    - "5432"
    volumes:
    - "database:/var/lib/postgresql/data:rw"
    - "database-dump:/mnt/data:rw"
    environment:
    - "POSTGRES_PASSWORD=${NC_DATABASE_PASSWORD}"
    - "POSTGRES_DB=nextcloud_database"
    - "POSTGRES_USER=nextcloud"
    - "TZ=${NC_TIMEZONE}"
    - "PGTZ=${NC_TIMEZONE}"
    stop_grace_period: "1800s"
    restart: "unless-stopped"
    shm_size: 268435456
    read_only: true
    tmpfs:
    - "/var/run/postgresql"
    cap_drop:
    - "NET_RAW"
    networks:
    - "nextcloud"

  nextcloud:
    depends_on:
      database:
        condition: "service_started"
        required: false
      redis:
        condition: "service_started"
        required: false
      clamav:
        condition: "service_started"
        required: false
      fulltextsearch:
        condition: "service_started"
        required: false
      talk-recording:
        condition: "service_started"
        required: false
      imaginary:
        condition: "service_started"
        required: false
    image: "ghcr.io/nextcloud-releases/aio-nextcloud:20251031_122139"
    init: true
    healthcheck:
      start_period: "0s"
      test: "/healthcheck.sh"
      interval: "30s"
      timeout: "30s"
      start_interval: "5s"
      retries: 3
    expose:
    - "9000"
    - "9001"
    volumes:
    - "nextcloud:/var/www/html:rw"
    - "nextcloud-data:/mnt/ncdata:rw"
    # - "${NC_NEXTCLOUD_TRUSTED_CACERTS_DIR}:/usr/local/share/ca-certificates:ro"
    environment:
    - "NEXTCLOUD_HOST=nextcloud"
    - "POSTGRES_HOST=database"
    - "POSTGRES_PORT=5432"
    - "POSTGRES_PASSWORD=${NC_DATABASE_PASSWORD}"
    - "POSTGRES_DB=nextcloud_database"
    - "POSTGRES_USER=nextcloud"
    - "REDIS_HOST=redis"
    - "REDIS_HOST_PASSWORD=${NC_REDIS_PASSWORD}"
    - "APACHE_HOST=apache"
    - "APACHE_PORT=${NC_APACHE_PORT}"
    - "NC_DOMAIN=${NC_DOMAIN}"
    - "ADMIN_USER=admin"
    - "ADMIN_PASSWORD=${NC_NEXTCLOUD_PASSWORD}"
    - "NEXTCLOUD_DATA_DIR=/mnt/ncdata"
    - "OVERWRITEHOST=${NC_DOMAIN}"
    - "OVERWRITEPROTOCOL=https"
    - "TURN_SECRET=${NC_TURN_SECRET}"
    - "SIGNALING_SECRET=${NC_SIGNALING_SECRET}"
    - "ONLYOFFICE_SECRET=${NC_ONLYOFFICE_SECRET}"
    - "CLAMAV_ENABLED=${NC_CLAMAV_ENABLED}"
    - "CLAMAV_HOST=clamav"
    - "ONLYOFFICE_ENABLED=${NC_ONLYOFFICE_ENABLED}"
    - "COLLABORA_ENABLED=${NC_COLLABORA_ENABLED}"
    - "COLLABORA_HOST=collabora"
    - "TALK_ENABLED=${NC_TALK_ENABLED}"
    - "ONLYOFFICE_HOST=onlyoffice"
    - "UPDATE_NEXTCLOUD_APPS=${NC_UPDATE_NEXTCLOUD_APPS}"
    - "TZ=${NC_TIMEZONE}"
    - "TALK_PORT=${NC_TALK_PORT}"
    - "IMAGINARY_ENABLED=${NC_IMAGINARY_ENABLED}"
    - "IMAGINARY_HOST=imaginary"
    - "CLAMAV_MAX_SIZE=${NC_APACHE_MAX_SIZE}"
    - "PHP_UPLOAD_LIMIT=${NC_NEXTCLOUD_UPLOAD_LIMIT}"
    - "PHP_MEMORY_LIMIT=${NC_NEXTCLOUD_MEMORY_LIMIT}"
    - "FULLTEXTSEARCH_ENABLED=${NC_FULLTEXTSEARCH_ENABLED}"
    - "FULLTEXTSEARCH_HOST=fulltextsearch"
    - "FULLTEXTSEARCH_PORT=9200"
    - "FULLTEXTSEARCH_USER=elastic"
    - "FULLTEXTSEARCH_INDEX=nextcloud"
    - "PHP_MAX_TIME=${NC_NEXTCLOUD_MAX_TIME}"
    # - "TRUSTED_CACERTS_DIR=${NC_NEXTCLOUD_TRUSTED_CACERTS_DIR}"
    - "STARTUP_APPS=${NC_NEXTCLOUD_STARTUP_APPS}"
    - "ADDITIONAL_APKS=${NC_NEXTCLOUD_ADDITIONAL_APKS}"
    - "ADDITIONAL_PHP_EXTENSIONS=${NC_NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS}"
    - "INSTALL_LATEST_MAJOR=${NC_INSTALL_LATEST_MAJOR}"
    - "TALK_RECORDING_ENABLED=${NC_TALK_RECORDING_ENABLED}"
    - "RECORDING_SECRET=${NC_RECORDING_SECRET}"
    - "TALK_RECORDING_HOST=talk-recording"
    - "FULLTEXTSEARCH_PASSWORD=${NC_FULLTEXTSEARCH_PASSWORD}"
    - "REMOVE_DISABLED_APPS=${NC_REMOVE_DISABLED_APPS}"
    - "IMAGINARY_SECRET=${NC_IMAGINARY_SECRET}"
    - "WHITEBOARD_SECRET=${NC_WHITEBOARD_SECRET}"
    - "WHITEBOARD_ENABLED=${NC_WHITEBOARD_ENABLED}"
    stop_grace_period: "600s"
    restart: "unless-stopped"
    cap_drop:
    - "NET_RAW"
    networks:
    - "internet"
    - "nextcloud"

  notify-push:
    image: "ghcr.io/nextcloud-releases/aio-notify-push:20251031_122139"
    user: "33"
    init: true
    healthcheck:
      start_period: "0s"
      test: "/healthcheck.sh"
      interval: "30s"
      timeout: "30s"
      start_interval: "5s"
      retries: 3
    expose:
    - "7867"
    volumes:
    - "nextcloud:/nextcloud:ro"
    environment:
    - "NC_DOMAIN=${NC_DOMAIN}"
    - "NEXTCLOUD_HOST=nextcloud"
    - "TZ=${NC_TIMEZONE}"
    - "REDIS_HOST=redis"
    - "REDIS_HOST_PASSWORD=${NC_REDIS_PASSWORD}"
    - "POSTGRES_HOST=database"
    - "POSTGRES_PORT=5432"
    - "POSTGRES_PASSWORD=${NC_DATABASE_PASSWORD}"
    - "POSTGRES_DB=nextcloud_database"
    - "POSTGRES_USER=nextcloud"
    restart: "unless-stopped"
    read_only: true
    cap_drop:
    - "NET_RAW"
    networks:
    - "nextcloud"

  redis:
    image: "ghcr.io/nextcloud-releases/aio-redis:20251031_122139"
    user: "999"
    init: true
    healthcheck:
      start_period: "0s"
      test: "/healthcheck.sh"
      interval: "30s"
      timeout: "30s"
      start_interval: "5s"
      retries: 3
    expose:
    - "6379"
    environment:
    - "REDIS_HOST_PASSWORD=${NC_REDIS_PASSWORD}"
    - "TZ=${NC_TIMEZONE}"
    volumes:
    - "redis:/data:rw"
    restart: "unless-stopped"
    read_only: true
    cap_drop:
    - "NET_RAW"
    networks:
    - "nextcloud"

  collabora:
    command: "${NC_ADDITIONAL_COLLABORA_OPTIONS}"
    image: "ghcr.io/nextcloud-releases/aio-collabora:20251031_122139"
    init: true
    healthcheck:
      start_period: "60s"
      test: "/healthcheck.sh"
      interval: "30s"
      timeout: "30s"
      start_interval: "5s"
      retries: 9
    expose:
    - "9980"
    environment:
    - "aliasgroup1=https://${NC_DOMAIN}:443,http://apache:23973"
    - "extra_params=--o:ssl.enable=false --o:ssl.termination=true --o:mount_jail_tree=false --o:logging.level=warning --o:logging.level_startup=warning --o:home_mode.enable=true --o:remote_font_config.url=https://${NC_DOMAIN}/apps/richdocuments/settings/fonts.json --o:net.post_allow.host[0]=.+"
    - "dictionaries=${NC_COLLABORA_DICTIONARIES}"
    - "TZ=${NC_TIMEZONE}"
    - "server_name=${NC_DOMAIN}"
    - "DONT_GEN_SSL_CERT=1"
    restart: "unless-stopped"
    cap_add:
    - "MKNOD"
    - "SYS_ADMIN"
    - "SYS_CHROOT"
    - "FOWNER"
    - "CHOWN"
    cap_drop:
    - "NET_RAW"
    networks:
    - "internet"
    - "nextcloud"

  talk:
    image: "ghcr.io/nextcloud-releases/aio-talk:20251031_122139"
    user: "1000"
    init: true
    healthcheck:
      start_period: "0s"
      test: "/healthcheck.sh"
      interval: "30s"
      timeout: "30s"
      start_interval: "5s"
      retries: 3
    expose:
    - "${NC_TALK_PORT}/tcp"
    - "${NC_TALK_PORT}/udp"
    - "8081"
    environment:
    - "NC_DOMAIN=${NC_DOMAIN}"
    - "TALK_HOST=talk"
    - "TURN_SECRET=${NC_TURN_SECRET}"
    - "SIGNALING_SECRET=${NC_SIGNALING_SECRET}"
    - "TZ=${NC_TIMEZONE}"
    - "TALK_PORT=${NC_TALK_PORT}"
    - "INTERNAL_SECRET=${NC_TALK_INTERNAL_SECRET}"
    restart: "unless-stopped"
    read_only: true
    tmpfs:
    - "/var/log/supervisord"
    - "/var/run/supervisord"
    - "/opt/eturnal/run"
    - "/conf"
    - "/tmp"
    cap_drop:
    - "NET_RAW"
    networks:
    - "core_cloudflared"
    - "nextcloud"

  talk-recording:
    image: "ghcr.io/nextcloud-releases/aio-talk-recording:20251031_122139"
    user: "122"
    init: true
    healthcheck:
      start_period: "0s"
      test: "/healthcheck.sh"
      interval: "30s"
      timeout: "30s"
      start_interval: "5s"
      retries: 3
    expose:
    - "1234"
    environment:
    - "NC_DOMAIN=${NC_DOMAIN}"
    - "TZ=${NC_TIMEZONE}"
    - "RECORDING_SECRET=${NC_RECORDING_SECRET}"
    - "INTERNAL_SECRET=${NC_TALK_INTERNAL_SECRET}"
    volumes:
    - "talk-recording:/tmp:rw"
    shm_size: 2147483648
    restart: "unless-stopped"
    read_only: true
    tmpfs:
    - "/conf"
    cap_drop:
    - "NET_RAW"
    networks:
    - "nextcloud"

  clamav:
    image: "ghcr.io/nextcloud-releases/aio-clamav:20251031_122139"
    user: "100"
    init: false
    healthcheck:
      start_period: "60s"
      test: "/healthcheck.sh"
      interval: "30s"
      timeout: "30s"
      start_interval: "5s"
      retries: 9
    expose:
    - "3310"
    environment:
    - "TZ=${NC_TIMEZONE}"
    - "MAX_SIZE=${NC_NEXTCLOUD_UPLOAD_LIMIT}"
    volumes:
    - "clamav:/var/lib/clamav:rw"
    restart: "unless-stopped"
    read_only: true
    tmpfs:
    - "/tmp"
    - "/var/log/clamav"
    - "/run/clamav"
    - "/var/log/supervisord"
    - "/var/run/supervisord"
    cap_drop:
    - "NET_RAW"
    networks:
    - "internet"
    - "nextcloud"

  # onlyoffice:
  #   image: "ghcr.io/nextcloud-releases/aio-onlyoffice:20251031_122139"
  #   init: true
  #   healthcheck:
  #     start_period: "60s"
  #     test: "/healthcheck.sh"
  #     interval: "30s"
  #     timeout: "30s"
  #     start_interval: "5s"
  #     retries: 9
  #   expose:
  #   - "80"
  #   environment:
  #   - "TZ=${NC_TIMEZONE}"
  #   - "JWT_ENABLED=true"
  #   - "JWT_HEADER=AuthorizationJwt"
  #   - "JWT_SECRET=${NC_ONLYOFFICE_SECRET}"
  #   volumes:
  #   - "onlyoffice:/var/lib/onlyoffice:rw"
  #   restart: "unless-stopped"
  #   cap_drop:
  #   - "NET_RAW"
  #   networks:
  #   - "internet"
  #   - "nextcloud"

  imaginary:
    image: "ghcr.io/nextcloud-releases/aio-imaginary:20251031_122139"
    user: "65534"
    init: true
    healthcheck:
      start_period: "0s"
      test: "/healthcheck.sh"
      interval: "30s"
      timeout: "30s"
      start_interval: "5s"
      retries: 3
    expose:
    - "9000"
    environment:
    - "TZ=${NC_TIMEZONE}"
    - "IMAGINARY_SECRET=${NC_IMAGINARY_SECRET}"
    restart: "unless-stopped"
    cap_add:
    - "SYS_NICE"
    cap_drop:
    - "NET_RAW"
    networks:
    - "nextcloud"
    read_only: true
    tmpfs:
    - "/tmp"

  fulltextsearch:
    image: "ghcr.io/nextcloud-releases/aio-fulltextsearch:20251031_122139"
    init: false
    healthcheck:
      start_period: "60s"
      test: "/healthcheck.sh"
      interval: "10s"
      timeout: "5s"
      start_interval: "5s"
      retries: 5
    expose:
    - "9200"
    environment:
    - "TZ=${NC_TIMEZONE}"
    - "ES_JAVA_OPTS=${NC_FULLTEXTSEARCH_JAVA_OPTIONS}"
    - "bootstrap.memory_lock=true"
    - "cluster.name=nextcloud"
    - "discovery.type=single-node"
    - "logger.level=WARN"
    - "http.port=9200"
    - "xpack.license.self_generated.type=basic"
    - "xpack.security.enabled=false"
    - "FULLTEXTSEARCH_PASSWORD=${NC_FULLTEXTSEARCH_PASSWORD}"
    volumes:
    - "elasticsearch:/usr/share/elasticsearch/data:rw"
    restart: "unless-stopped"
    cap_drop:
    - "NET_RAW"
    networks:
    - "nextcloud"

  whiteboard:
    image: "ghcr.io/nextcloud-releases/aio-whiteboard:20251031_122139"
    user: "65534"
    init: true
    healthcheck:
      start_period: "0s"
      test: "/healthcheck.sh"
      interval: "30s"
      timeout: "30s"
      start_interval: "5s"
      retries: 3
    expose:
    - "3002"
    tmpfs:
    - "/tmp"
    environment:
    - "TZ=${NC_TIMEZONE}"
    - "NEXTCLOUD_URL=https://${NC_DOMAIN}"
    - "JWT_SECRET_KEY=${NC_WHITEBOARD_SECRET}"
    - "STORAGE_STRATEGY=redis"
    - "REDIS_HOST=redis"
    - "REDIS_HOST_PASSWORD=${NC_REDIS_PASSWORD}"
    - "BACKUP_DIR=/tmp"
    restart: "unless-stopped"
    read_only: true
    cap_drop:
    - "NET_RAW"
    networks:
    - "nextcloud"

volumes:
  apache:
  clamav:
  database:
  database-dump:
  elasticsearch:
  nextcloud:
  onlyoffice:
  redis:
  talk-recording:
  nextcloud-data:


networks:
  core_cloudflared:
    external: true

  nextcloud:
    internal: true
