cluster_name: "trappist-1"
kubeconfig_path: "./out/kubeconfig"
k3s_version: "v1.34.1+k3s1"

image: "rocky-10"

networking:
  ssh:
    port: 22
    use_agent: false
    public_key_path: "~/.ssh/trappist-1.pub"
    private_key_path: "~/.ssh/trappist-1"

  allowed_networks:
    ssh:
    - 0.0.0.0/0
    api:
    - 10.0.0.0/16
    - "5.145.72.38/32" # TODO: remove

  public_network:
    ipv4: true
    ipv6: true

  private_network:
    enabled: true
    subnet: 10.0.0.0/16

  cni:
    enabled: true
    encryption: false
    mode: flannel

masters_pool:
  instance_type: cx23
  instance_count: 3
  locations:
  - fsn1
  - hel1
  - nbg1

worker_node_pools:
- name: workers
  instance_type: cx23
  instance_count: 3
  location: nbg1
  autoscaling:
    enabled: true
    min_instances: 1
    max_instances: 5

protect_against_deletion: true
create_load_balancer_for_the_kubernetes_api: true

embedded_registry_mirror:
  enabled: true
