config: {}

networks:
- name: "incusbr0"
  type: "bridge"
  project: "default"
  description: ""
  config:
    ipv6.address: "fd42:a85f:f1ee:2344::1/64"
    ipv6.nat: "true"

storage_pools:
- name: "default"
  driver: "btrfs"
  description: ""
  config:
    size: "30GiB"
    source: "/var/lib/incus/disks/default.img"

storage_volumes: []

profiles:
- name: "default"
  project: "default"
  description: "Default Incus profile"
  config: {}
  devices:
    root:
      path: "/"
      type: "disk"
      pool: "default"
    eth0:
      name: "eth0"
      network: "incusbr0"
      type: "nic"

projects:
- name: "default"
  description: "Default Incus project"
  config:
    features.images: "true"
    features.networks: "true"
    features.networks.zones: "true"
    features.profiles: "true"
    features.storage.buckets: "true"
    features.storage.volumes: "true"
